<?php 
function custom_profile_form_views_pre_render (&$view) {
	//die;

    
}
		
function custom_profile_form_form_alter(&$form, &$form_state, $form_id)
{	
	if($form_id == 'views_exposed_form') {

		 $view = $form_state['view'];
		 if ($view->name == 'learners_list') {
            // alter your exposed form here
  
            if(!empty($_REQUEST)) {
    			if(isset($_SESSION['filter'])) {
						unset($_SESSION['filter']);
    			}
				foreach ($_REQUEST as $key => $value) {
						$_SESSION['filter'][$key] = $value;
				}		
			}

			if(isset($_SESSION['filter'])) {
				foreach ($_SESSION['filter'] as $key => $value) {
					$form[$key]['#value'] = $value;
					$_POST[$key] = $value;
				}
			}
        }	
	}

	if ($form_id == 'user_profile_form')	
	{	

		$form['actions']['#weight'] = -1000;
		$form['actions']['cancel']['#value'] = t('Delete Account');

		unset($form['actions']['submit']);

		$form['action-bar']= array(
				'#type' => 'container',
				'#value' => 'Exapand All',
				'#weight' => -1000,
			);

		$form['actions']['#prefix'] = '<div id="action-bar" class="form-actions wrapper">';
		$form['actions']['#suffix'] = '</div>';

		$form['actions']['submit']= array(
				'#type' => 'submit',
				'#value' => 'save',
				'#weight' => -1000
				);
	
		if(arg(3)=='plan_content')
		{
			
			$form['actions']['expand-all'] = array(
				'#type' => 'button',
				'#value' => 'expand all',
				'#weight' => -10
				);

			$form['actions']['collapse-all'] = array(
				'#type' => 'button',
				'#value' => 'Collapse all',
				'#weight' => -11
				);
		}

		global $user;
			
		if(in_array('practitioner', $user->roles))
		{
			unset($form['account']['pass']);
		}

		if(in_array('practitioner', $user->roles))
		{	
			$existing = user_load(arg(1));

			if(isset($existing->status))
			{	
				if($existing->status == 0)
				{
					unset($form['action-bar']);
					unset($form['submit']);
					unset($form['profile_learner_profile']['submit']);
					unset($form['profile_follow_ups']['submit']);
					unset($form['profile_exit_information']['submit']);
					unset($form['profile_plan_content']['submit']);
				}

			}
			
		}

		if(arg(0) == 'user' && arg(2) == 'edit' && arg(3) == '')
		{	
			if(isset($form['#user']->field_courses_4['und']))
			{	
				$courselist = '';

				if (!function_exists('in_array_r'))
				{
					function in_array_r($needle, $haystack, $strict = false) {
					    foreach ($haystack as $item) {
					        if (($strict ? $item === $needle : $item == $needle) || (is_array($item) && in_array_r($needle, $item, $strict))) {
					            return true;
					        }
					    }

					    return false;
					}
				}
				foreach ($form['#user']->field_courses_4['und'] as $key => $value) { 

				  	$cid = $value['target_id'];
				  	$nid = node_load($cid);				  

				  	$time_v = '';
					if(isset($nid->field_time['und']))
			  		{
			  			$count = count($nid->field_time['und']);
			  		}
			  		else
			  		{
			  			$count = '';
			  		}
				
				  	if(in_array_r($nid->nid, $form['#user']->field_courses_4) == 1)
					{	
						foreach ($form['#user']->field_courses_live as $key => $value) {
							$id = [];
							$time = [];
							$group = [];
							foreach ($value as $key => $value) {
								
								  $data = explode(',', $value['value']);
								  $id1 = $data[0];
								  $time1 = $data[1];
								  $group1 = array('gp'=> array('id'=>$id1,'time'=>$time1));
								  array_push($group,$group1);

							}
						}
						if(isset($group))
						{
							foreach ($group as $key => $value) {
		                  	
		                  	if(in_array_r($nid->nid, $value))
							{   
								$time_v = $value['gp']['time'];
								break;
							}
							else
							{
								$time_v = '';
							}

		                  }
						}
					}
			
				  	if($nid->type == 'courses_live')
				  	{	
					  	$class_type = '('.$nid->field_type_of_class['und'][0]['value'].')';
					  
					  	$timestamp = strtotime($nid->field_time['und'][0]['value']); 
					  	$user_tz = new DateTimeZone('America/Toronto');  
						$offset = $user_tz->getOffset(new DateTime($nid->field_time['und'][0]['value']));
						$start_stamp = $timestamp + $offset;
			 	  		$time_n = format_date($start_stamp, 'custom', 'd/m/y h:i a');		 
				  	}
				  	else
				  	{
					  	$class_type = '';
					  	$time_n = '';
				  	}

					if($count>1 && $time_v != '')
					{
						$time = $time_v;
					}
					else
					{
						$time = $time_n;
					}
			
				  	$courselist .= '<span>'.$nid->title.' '.$class_type. ' </br>'.$time.PHP_EOL .'<hr></span>';
				}

				$form['account']['cList'] = array(
				'#type' => 'markup',
				'#markup' => '<div class="form-type-markup" id="course-list-admin"><label>Courses List</label><div>'. $courselist .'</div></div>',
				'#weight' => 10
				);
			}
			$user_id = arg(1);

			$form['field_client_id']['und'][0]['markup']= array(
			'#type' => 'markup',
			'#markup' => '<div class="form-type-markup"><label>Client ID</label><div>'. $user_id .'</div></div>',
			'#weight' => 10
			);

			$profiles = profile2_load_by_user($form['#user']->uid,'learner_profile');

		
			if(isset($profiles->created))
			{
				$form['field_register_date']['und'][0]['markup']= array(
				'#type' => 'markup',
				'#markup' => '<div class="form-type-markup"><label>Registration Date</label><div>'. format_date($form['#user']->created, 'custom', 'd/m/Y H:ia').'</div></div>',
				'#weight' => 11
				);
			}
					
		}

		unset($form['account']['status']);	
	}
}
