
<?php 
function milestone_values_user_presave(&$edit, $account, $category) {

	if(isset($edit['profile_learner_profile']) || isset($edit['profile_plan_content']))
	{
		$number_of_milestones = count($edit['profile_plan_content']['field_learner_plan1']['und']['entities']);
		$edit['profile_learner_profile'] = array('field_number_of_milestones1' => array('und' => array(array('value' => $number_of_milestones))));
		echo $edit['profile_learner_profile']['field_number_of_milestones1']['und'][0]['value'];

		$profiles = profile2_load_by_user($account);
		$learner_profile = $profiles['learner_profile'];
		$learner_profile->field_number_of_milestones1['und'][0] = array('value' => $number_of_milestones);
		profile2_save($learner_profile);
	}

}

?>